config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'leagues#show', :id => 1

  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create]
  resources :leagues, only: :show
  resources :seasons, only: :show
  resources :owners, only: :show
  resources :teams, only: [:index, :show]
  resources :games, only: :show
  resources :records, only: :index
  resources :votes, only: :create
  resources :bowerytimes, only: :index

  get 'session/logout' => "session#logout"
  get 'application/session_viewer' => "application#session_viewer"
  get 'application/contact' => "application#contact"
  get 'application/headtohead' => "application#headtohead"
  post 'application/headtoheadresult' => "application#headtoheadresult"
  get 'application/alltimestats' => "application#alltimestats"
end

app/models/league.rb
class League < ApplicationRecord
  has_many :seasons
  has_many :teams, through: :seasons
  has_many :owners, -> { distinct }, through: :teams
  has_many :games, through: :seasons
  has_many :champions, through: :seasons, source: :teams

  validates :name, presence: true

  def generate_all_time_stats(stat, game_type)
    stats_array = []
    owners.each do |owner|
      owner_hash = owner.owner_stats(game_type)
      owner_hash[:name] = owner.full_name
      stats_array.push(owner_hash)
    end
    stats_array
  end

  def owner_season_records(game_type)
    records = {}
    owners.each do |owner|
      owner_hash = {}
      owner.teams.each do |team|
        ts = team.team_stats(game_type)
        owner_hash[team.season.year] = [ts[:wins], ts[:losses]]
      end
      records[owner.first_name] = owner_hash
    end
    records
  end

  def standings(game_type)
    owners.sort { |x,y| y.over_500(game_type) <=> x.over_500(game_type) }
  end

  def avg_ppg
    total_points = 0
      games.each { |game| total_points += (game.away_score + game.home_score) }
    (total_points / (games.count * 2)).round(1)
  end

  def avg_point_differential
    total = 0
    games.each { |game| total += (game.away_score - game.home_score).abs }
    (total / games.count).round(1)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def show
    @league = League.find(params[:id])
    @teams = @league.teams
    @seasons = @league.seasons
    @first_five = Game.where(completed?: false).first(5)
  end

end

app/views/leagues/show.html.erb
<div class="col-lg-8 col-md-8">
  <h3>News Articles</h3>

  <h4>What Makes a Player ELITE?</h4>
  <p>Lately there has been much discussion amongst owners in
  the BMFFL about what makes a player ELITE. The
  conversation has centered around a certain few athletes.
  (And before I say who they are I just want to say that if
  you're going to go after an amateur athlete, if you're going
  to go after one of my athletes, especially one who does
  everything right, except poke opponents in the eyes, then
  you better come after me, because I'm a man, I'm 40, I'm
  not a kid, that's why I don't read the Bowery Times, because
  it's garbage, and the senior editor doesn't have his facts
  straight). Anyway, this prestigious club of (potential)
  ELITE athletes includes the likes of Joe Flacco, the great
  Sioux City product Adam Woodbury, and yesterday the
  question was posed as to whether Jay Cutler is ELITE.
  Seriously? There are three criteria that are used to determine if an
  athlete is ELITE:
  <ol>
    <li>Individual Performance. An elite athlete must have
    statistics that are well above the league standard.</li>
    <li>Championships. You've gotta win championships. You
    can talk about how great Archie Manning was all day long,
    but the guy didn't win squat. And he played at Ole Miss.
    Which isn't as bad as Mississippi State though. If you're not
    familiar with Mississippi State, they're kind of about as
    good at Matt's fantasy team on a year to year basis.</li>
    <li>The eye test. You know an ELITE athlete when you see
    one. This is the criteria that fuels most debates as to
    whether or not an athlete is ELITE.</li>
  </ol>
  Now, let's look at a couple of examples of ELITE players.
  I'll include players from a few different sports. These
  players can be from the past or the present. </p>

  <p> ELITE: Derek Jeter, Peyton Manning, Patrick Kane,
  Michael Jordan, Tiger Woods, Anthony Rizzo</p>
  <p>Not ELITE: Derrick Rose, the Michigan punter, Augie
  Ojeda</p>
  <p>Now for each of the three athletes that we've been
  talking about for the past couple weeks:</p>

  <ol>
    <li>Joe Flacco - ELITE. Joe has some great career numbers,
    is a champion, and looks damn good out there.</li>
    <li>Adam Woodbury - ELITE. Guy records some really
    high stats (personal fouls), guy is a champion (won an
    NCAA tournament game last year), and the guy looks
    great out there. And he invented the eye poke of the
    opponent that has the ball.</li>
    <li>Jay Cutler - ELITE. Did you guys see that fourth quarter
    game winning drive on Monday night?</li>
  </ol>

</div>

<div class="col-lg-4 col-md-4">
  <h3>BMFFL Polls</h3>
  <% if !logged_in?  %>
    <h5 class="gray">Login or Register to Vote!</h5>
  <% end %>

  <ul class="list-group" id="polls">
    <% @first_five.each do |game| %>
      <% @away_team_stats = game.away_team.team_stats("All") %>
      <% @home_team_stats = game.home_team.team_stats("All") %>
      <li class="list-group-item polls-right">
        <div class="team-name-polls">
          <% if current_user %>
            <%= form_tag(votes_path, method: :create, remote: true) do %>
              <% if voted_on? %>
                <p><%= game.away_team.name %> (<%= @away_team_stats[:wins] %>-<%= @away_team_stats[:losses] %>-<%= @away_team_stats[:ties] %>)</p>
                <p><%= game.home_team.name %> (<%= @home_team_stats[:wins] %>-<%= @home_team_stats[:losses] %>-<%= @home_team_stats[:ties] %>)</p>
                <h6><%= game.away_team.name %>: <%= game.votes.select { |vote| vote.team_id == game.away_team.id }.count %> - <%= game.home_team.name %>: <%= game.votes.select { |vote| vote.team_id == game.home_team.id }.count %></h6>
              <% else %>
                <p><%= radio_button_tag 'vote[team_id]', game.away_team.id %>
                <%= game.away_team.name %> (0-0-0)</p>
                <p><%= radio_button_tag 'vote[team_id]', game.home_team.id %>
                <%= game.home_team.name %> (0-0-0)</p>
                <%= hidden_field_tag('vote[game_id]', game.id) %>
                <%= hidden_field_tag('vote[voter_id]', session[:user_id]) %>
                <%= submit_tag 'Vote!' %>
              <% end %>
            <% end %>
          <% else %>
            <p><%= game.away_team.name %> (<%= @away_team_stats[:wins] %>-<%= @away_team_stats[:losses] %>-<%= @away_team_stats[:ties] %>)</p>
            <p><%= game.home_team.name %> (<%= @home_team_stats[:wins] %>-<%= @home_team_stats[:losses] %>-<%= @home_team_stats[:ties] %>)</p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>