config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'leagues#show', :id => 1

  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create]
  resources :leagues, only: :show
  resources :seasons, only: :show
  resources :owners, only: :show
  resources :teams, only: [:index, :show]
  resources :games, only: :show
  resources :records, only: :index
  resources :votes, only: :create
  resources :bowerytimes, only: :index

  get 'session/logout' => "session#logout"
  get 'application/session_viewer' => "application#session_viewer"
  get 'application/contact' => "application#contact"
  get 'application/headtohead' => "application#headtohead"
  post 'application/headtoheadresult' => "application#headtoheadresult"
  get 'application/alltimestats' => "application#alltimestats"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>BMFFL</title>
        <%= csrf_meta_tags %>
        <%= action_cable_meta_tag %>
        <%= favicon_link_tag 'football.jpeg' %>

        <%= javascript_include_tag 'application' %>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.min.css">
        <!-- My CSS file -->
        <link rel="stylesheet" type="text/css" href="/css/main.css">
    </head>

    <body>
        <div id="wrapper">
            <header>
                <ul class="list-group">
                    <% Game.where(completed?: true).last(5).each do |game| %>
                        <li class="list-group-item scoreboard">
                            <p class="game-date">12/01 - 12/05</p>
                            <div class="team-name col-lg-10">
                                <p><%= game.away_team.abbr %></p>
                                <p><%= game.home_team.abbr %></p>
                            </div>
                            <div class="team-score col-lg-2">
                                <p><%= game.away_score %></p>
                                <p><%= game.home_score %></p>
                            </div>
                        </li>
                    <% end %>
                </ul>

                <nav class="navbar navbar-default" role="navigation">
                    <div class="green">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="tab"><%= link_to "Home", root_path %></li>
                                <li class="dropdown tab-left">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seasons <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <% League.first.seasons.each do |season| %>
                                            <li class="tab"><%= link_to season.year, season %></li>
                                        <% end %>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Owners <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <% League.first.owners.sort.each do |owner| %>
                                            <li class="tab"><%= link_to owner.first_name + ' ' + owner.last_name, owner %></li>
                                        <% end %>
                                    </ul>
                                </li>
                                <li class="tab"><%= link_to "Teams", teams_path %></li>
                                <li class="tab"><%= link_to "Head-To-Head", application_headtohead_path %></li>
                                <li class="tab"><%= link_to "All-Time Stats", application_alltimestats_path %></li>
                                <li class="tab"><%= link_to "Contact", application_contact_path %></li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                <% if current_user %>
                                    <li class="tab"><%= link_to current_user.username, user_path(current_user) %></li>
                                    <li class="tab"><%= link_to "Logout", session_logout_path %></li>
                                <% else %>
                                    <li class="tab"><%= link_to "Login", new_session_path %></li>
                                    <li class="tab-right"><%= link_to "Register", new_user_path %></li>
                                <% end %>
                            </ul>
                        </div><!-- /.collapse navbar-collapse -->
                    </div><!-- /.green -->
                </nav>
            </header>

            <div id="content">
                <div class="container">
                    <%= yield %>
                </div>
            </div>

            <footer>
                <p class="footer-text">© 2016 BMFFL Advanced Media, LP. All rights reserved.</p>
                <p class="footer-text">817 Bowery St.</p>
                <p class="footer-text">Iowa City, Iowa, 52240</p>
            </footer>
        </div>
    </body>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="/js/application.js"></script>
    <script src="/js/bootstrap.min.js"></script>
</html>